services:
  signaling:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      SIGNALING_SETTINGS_SECRET_KEY: ${SIGNALING_SETTINGS_SECRET_KEY}
      SIGNALING_SETTINGS_LOCAL_SETTINGS_PATH: ${SIGNALING_SETTINGS_LOCAL_SETTINGS_PATH}
      SIGNALING_SETTINGS_ALLOWED_HOSTS: ${SIGNALING_SETTINGS_ALLOWED_HOSTS} 
      SIGNALING_SETTINGS_CORS_ALLOWED_ORIGINS: ${SIGNALING_SETTINGS_CORS_ALLOWED_ORIGINS}
